### ISSUE TITLE
Doesn't work on Canon EOS 250d

### ISSUE THREAD

**Issue by nm17** [maxmacstn/ESP32-Canon-BLE-Remote#3]
Pairs fine, but no reaction to focus or shutter buttons

**Comment by ghost** [comment]
I had that Issue too. You have to set the Trigger Mode of the Camera to "Remote and Timed"
![grafik](https://user-images.githubusercontent.com/20189750/212125067-a48e46aa-8043-45f9-8eed-5922856c8254.png)
(thats what it looks like)

**Comment by nm17** [comment]
OMG, I hope it's that easy, will try it out and say if it helps

**Comment by nm17** [comment]
@hannesfischer where is that option located? I can't find it

**Comment by ghost** [comment]
In the main screen its right here:
![grafik](https://user-images.githubusercontent.com/20189750/212529847-6786a9cf-945c-4aaf-a358-e8550358b36e.png)

You have to press the "Q" button before you can change this

**Comment by nm17** [comment]
Ok, got it working! Can this project start/stop recording of a video?

**Comment by ghost** [comment]
I belive it cant. I havent got that working either.

**Comment by maxmacstn** [comment]
Remote start/stop video recording is working fine with my M50

You need to enable the remote in video mode first by:

Switch to video mode -> Setting -> Remote Control -> Enable 

![telegram-cloud-photo-size-5-6253660064913143320-y](https://user-images.githubusercontent.com/19774345/215790148-43007e69-83c5-440c-abac-92145e0c75b5.jpg)
